### ISSUE TITLE
Migrate to the latest version of Fundamental-UI

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-react#1]
Go through all implemented react components and make sure they are consistent with the latest version of Fundamental-UI (1.2.2)

**Comment by droshev** [comment]
@InnaAtanasova did we do that already?

**Comment by InnaAtanasova** [comment]
Not yet! Some components need refactoring (Action Bar, Tree, Table, etc.). Now that we have Dropdown (now consisting of Popover and Menu) consistent with the latest version of fundamental-ui, we can start working on these components.

**Comment by InnaAtanasova** [comment]
Check [here](https://github.com/SAP/fundamental-react/issues/45)
