### ISSUE TITLE
Username is cut off from Shellbar with no margin in the top...

### ISSUE THREAD

**Issue by miltonchandradas** [SAP/fundamental-react#1002]
### Description
Username is cut off from Shellbar with no margin in the top...
See attached image

### Versions
**fundamental-react:**
![ShellbarIssue](https://user-images.githubusercontent.com/47120473/81092588-cf447a00-8ece-11ea-9d76-97467c4f9312.jpg)

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
I think the solution here is to change the placement of the popper to bottom-right like the other popovers in the shellbar: https://github.com/SAP/fundamental-react/blob/master/src/Shellbar/Shellbar.js#L420

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/1008
