### ISSUE TITLE
Substring search doesn't work in SearchInput

### ISSUE THREAD

**Issue by muthukkaruppan4695** [SAP/fundamental-react#1003]
**Version :** I am using fundamental-react version : **0.9**
**Issue :** Substring search doesn't work in SearchInput.
Example : Below values are present in my searchList
1) Who is a supplier user?
2) How to set the PIN?
3) Who is a buyer user?
4) How to change the PIN if I forget it?
Key to be searched : 
a)Who : return option 1,3 [CORRECT]
b)How : return option 2,4 [CORRECT]
c) PIN : empty result  **Issue** [Should return 2,4]
d) user : empty result  **Issue** [Should return 1,3]

Current Behaviour : Search key is compared only with the starting characters in the search list.
FIX :  Search key should be compared with the substring in the search list.

**Comment by BenOron** [comment]
Hi @jbadan,
Maybe you have some input for this ticket? 

Thanks
Ben

**Comment by jbadan** [comment]
I haven't had much time to look at it - feel free to open a pr :)
