### ISSUE TITLE
getting value from 'onSelect' regarding the Select component 

### ISSUE THREAD

**Issue by nickbaek** [SAP/fundamental-react#1004]
### Description
Hi Team,
I saw your great works on the newly changed components. Appreciated.
I'm trying to get value from the Select list but I don't know how can I retrieve the values.
![image](https://user-images.githubusercontent.com/22496498/81242715-d1cadf00-9048-11ea-9e06-22ea822f3038.png)
Can anyone help..?

### Versions
**fundamental-react: 0.9.0

**Comment by jbadan** [comment]
Hi Nick! Your onSelect function should return with an object: `{event, option}`
See: https://github.com/SAP/fundamental-react/blob/master/src/Select/Select.js#L94

Thanks for pointing this out! I will add an issue to add this information to the documentation website.
