### ISSUE TITLE
SearchInput doesn't updated when searchList property change 

### ISSUE THREAD

**Issue by I065450** [SAP/fundamental-react#1012]
Version : 
I am using fundamental-react version : 0.9 
Issue : 
SearchInput doesn't update when searchList change.

Example : 
I build the SearchInput with empty list till I get response from the server,
the control remain empty, since you read the list only in the constructor or when pressing ESC.

Current Behaviour : once SearchInput render it is not updated when searchList property change 
FIX : searchList should be read again in componentDidUpdate()

**Comment by jbadan** [comment]
Hello! Please feel free to open a pr if you'd like to contribute :)
