### ISSUE TITLE
ComboboxInput: should filter based on FormInput input

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-react#1019]
### Description

ComboBox input should filter the dropdown + enable selection via the FormInput. This is necessary for the replacement of SearchInput (no longer supported in fundamental styles)

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by prsdthkr** [comment]
Referring to spec is Example 3 here: https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html
