### ISSUE TITLE
Shellbar does not provide a way to pass Popover props to Search Input

### ISSUE THREAD

**Issue by mdhender** [SAP/fundamental-react#1020]
### Description
It looks like there's no way to pass props through the Shellbar's search box to the popover used to display the list.

I ran into this on Chrome 83.0.4103.56 on Mac 10.15.4 with the window set to 1200x600. I copied the example "Links with collapsible menu, CoPilot and Product Switch" Shellbar from the docs (https://sap.github.io/fundamental-react/shellbar) to a new React app and had the App function return only the Shellbar:

```javascript
function App() {
   return <Shellbar ... />
}
```

Running the app, then clicking in the search input box causes the search list to be displayed above the search input box. Making the window bigger causes the list to be displayed below the search input box, as expected.

It looks like this could be fixed by passing {disableEdgeDetection:true, placement:"bottom"} to the Popover, but the Shellbar's SearchInput interface doesn't pass those props through.

### Versions
**fundamental-react: 0.9.0**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by prsdthkr** [comment]
@mdhender you may now pass popover props to Shellbar.searchInput. They are defaulted to 
```
{
   placement:'bottom',
   disableEdgeDetection: true
}
```
