### ISSUE TITLE
Select: Readonly state for Select is not working

### ISSUE THREAD

**Issue by cham2017** [SAP/fundamental-react#1053]
### Description
Dear developer,
I followed the instructions as below:
https://sap.github.io/fundamental-styles/components/select.html
> To make the Select component read-only, the readonly attribute needs to be added to the fd-select__control element. This can also be done by adding the .is-readonly class or the aria-readonly="true" attribute.

My code is like below. However the Select that rendered is still same as the usual one.

```
const { toolTip, enabled = true, visible = true, readOnly = false } = props;
const readOnlyProperty = readOnly ? "true" : "false";
import "fundamental-styles/dist/select.css";
import { Select } from "fundamental-react";
  const dropDownListBoxClass = classnames(
    "fd-select--compact",
    readOnly ? "is-readonly" : ""
  );
<Select className={dropDownListBoxClass} title={toolTip} disabled={!enabled} aria-readonly={readOnly}></Select>
```

### Versions
**fundamental-react:**
0.9.0
---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Hi @cham2017 ! Thanks for using fundamental-react! 

The instructions you've linked are for using fundamental-styles, not fundamental-react. We seem to be missing the readonly state from our component. In this case, following the instructions for fundamental-styles will not work as we spread props differently and it looks like the readonly state has a different underlying html structure and is not simply an added attribute.

Check out the fundamental-react docs for Select here: https://sap.github.io/fundamental-react/?path=/docs/component-api-select--primary

The `Select` component already imports the styles from fundamental-styles, so the `import "fundamental-styles/dist/select.css";` is unnecessary. We also already have a `compact` attribute, no need to add your own class. Once the linked pr is merged, your code should look like: 
```
import { Select } from "fundamental-react";

const { toolTip, enabled = true, visible = true, readOnly = false } = props;

<Select title={toolTip} compact disabled={!enabled} readOnly={readOnly} />
```

Although I'm not sure what the `title` prop is - did you mean `placeholder`?

**Comment by cham2017** [comment]
Hi @jbadan 
Thanks for the quick action and your suggestion. 
Regarding the title prop, it means tooltip which appears when mouse over the Select control.
