### ISSUE TITLE
"hello world" app

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental-react#1085]
I am looking for a simple fundamental-react app, with couple of form input fields.

Any example I could start from?

Thanks in advance.

**Comment by jbadan** [comment]
Hi @bsrdjan! We have an issue in our backlog to standup an app, but in the meantime, we are setup to integrate with create-react-app pretty seamlessly. I put this together in a few minutes (although the forms are not wired up - purely presentational): https://github.com/jbadan/fundamental-react-test-app
