### ISSUE TITLE
Implement Pagination Component

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-react#11]
[Pagination](https://sap.github.io/fundamental/components/pagination.html)

**Comment by InnaAtanasova** [comment]
Can we close this issue?

**Comment by chrismanciero** [comment]
There is still the open question about how to handle the ... in the control. This thread discusses some of the issues (https://github.com/SAP/fundamental-react/pull/23) but I still have questions on how this control should work. 

Should this issue be closed and maybe a new one created on implementing the ... once the functionality is better defined?

Some more questions:
- Is there a minimum number of pages needed before displaying the ellipsis?
- If on a page and the next/previous item is ... when clicking next/previous does the ... expand to show more page numbers or just insert the next/previous page before/after the ellipsis. Example:
**1 2 3 ... 35**, after clicking previous does it go to **1 2 3 ... 34 35**
- If the component went with the solution from the question above (**1 2 3 ... 34 35**). If the previous button was hit 30 more times the pagination control will show all pages 1 through 35. How does the component choose where to insert the ... again?
