### ISSUE TITLE
Need option to pre-select productSwitchItem in Shellbar component 

### ISSUE THREAD

**Issue by athulvraj** [SAP/fundamental-react#1107]
### Description
Product switch item in the Shellbar component does not have an option to show as preselected 

### Versions
**fundamental-react:**  0.10.1

---
Product switch item selection is available in fundamental styles
https://sap.github.io/fundamental-styles/components/shellbar.html

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/1108
