### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#111]
Looking through the dependencies, it appears some of the dependencies can be moved to devDependencies and some can be moved to peerDependencies.  Organizing dependencies properly can dramatically reduce the size of the package.

CORUI-5995

**Comment by bcullman** [comment]
we should report package size with this, and get before and after numbers.

**Comment by jeffredodd** [comment]
@bcullman I think this would be more of a build time process but it won't quite work until #105 is competed.

**Comment by bcullman** [comment]
@jeffredodd sounds reasonable. I was aiming to show improvement, but it is clear there are 2 different tasks here.
