### ISSUE TITLE
Cannot display text within Checkbox of Table

### ISSUE THREAD

**Issue by yingzoe** [SAP/fundamental-react#1120]
Hi Team,
I'm using the Checkbox inside the Table but to find that text is missing, I even tried your sample here: https://sap.github.io/fundamental-react/?path=/docs/component-api-table--primary.

However, the text within the Checkbox component is not displayed either. You can find the screenshot below.
Could you please help me with it?

### Versions
**fundamental-react:**
0.10.1
---
![image](https://user-images.githubusercontent.com/12248949/86764035-569e9d00-c07a-11ea-8a2d-ab08db3cff8f.png)

It seems that the Label tag is not constructed well.
Your sample:
![image](https://user-images.githubusercontent.com/12248949/86765578-eabd3400-c07b-11ea-8d88-1613632547cf.png)

Mine:
![image](https://user-images.githubusercontent.com/12248949/86765686-13452e00-c07c-11ea-8cf9-eece4d95c1fc.png)

**Comment by jbadan** [comment]
Hi @yingzoe! Thanks for using fundamental-react. Can you check what version of fundamental-react you are using? `npm ls fundamental-react`

The html output you're seeing was changed from the one you see in your sample to the one you see in our sample in `0.8.0-rc.32`

**Comment by yingzoe** [comment]
Hi @jbadan, here is the result:
+-- @eureka/ui-utils@0.0.93
| `-- @eureka/ui-framework@0.0.47
|   `-- fundamental-react@0.8.1
`-- fundamental-react@0.10.1

**Comment by jbadan** [comment]
@yingzoe That looks like you need to update `@eureka/ui-framework` - you could also try `npm dedupe`

**Comment by jbadan** [comment]
@yingzoe I'm going to close this issue. Feel free to reopen if you don't agree that it is solved.
