### ISSUE TITLE
Add tree shaking

### ISSUE THREAD

**Issue by mobot11** [SAP/fundamental-react#113]
Update library to be tree-shakable. https://webpack.js.org/guides/tree-shaking/

CORUI-5996

**Comment by jiawang1** [comment]
not quite clear this meaning of this?  Do you mean compile this project to ES6 modules so that other people who want to use this could only bundle which components it really use?

**Comment by mobot11** [comment]
After looking into this I think our best bet is to point consumers to import from `dist` ex. 

```
import Alert from 'fundamental-react/dist/Alert/Alert';
```

until https://nodejs.org/api/esm.html lands in node officially. Will update Readme and docs.

**Comment by mobot11** [comment]
Closing in favor of https://github.com/SAP/fundamental-react/issues/314.
