### ISSUE TITLE
Remove react router as a dependency

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental-react#115]
This should allow consumers to use React-Router 4 which will allow for greater code splitting of applications.

CORUI-5993

**Comment by droshev** [comment]
@bcullman the link to your JIRA requires user

**Comment by InnaAtanasova** [comment]
@bcullman , we are using react-router for the documentation components. If we separate the documentation, do you think we still need to remove react router as a dependency?

**Comment by jiawang1** [comment]
some components depends on react router: Breadcrum, Menu, tabs....

**Comment by bcullman** [comment]
@jiawang1 they will need to be re-written so that they operate using props and not a direct dependency on react-router.
