### ISSUE TITLE
The  "@types/fundamental-react" not being consistent with fundamental-react

### ISSUE THREAD

**Issue by Vita-Meow** [SAP/fundamental-react#1190]
### Description
Is there anything we can do , make we can use the latest type definition of fundamental-react, because we're using typescript, it would be very convenient then we can see the types when we using it . Thank you ~
### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Hi @Vita-Meow! The core fundamental-react team doesn't have the bandwidth to keep the types package updated at this moment. We are happy to review if you or your team would like to update it!
