### ISSUE TITLE
Update the selected state when props change: < MultiInput />

### ISSUE THREAD

**Issue by bekza** [SAP/fundamental-react#1208]
### Description
Similar to #1193 other components will need to respond to changes of the selected state after the initial render.

The MultiInput has a state here: 
https://github.com/SAP/fundamental-react/blob/master/src/MultiInput/MultiInput.js#L26 
but that state is not controlled by future prop changes.

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by skvale** [comment]
This was similar enough to combine into https://github.com/SAP/fundamental-react/issues/1201
