### ISSUE TITLE
Running `npm run build` under Windows fails due to usage of `rm` in the build script - please use cross-platform alternative like rimraf

### ISSUE THREAD

**Issue by huberv** [SAP/fundamental-react#1246]
### Description

I cloned the repository under Windows and run `npm i` (works) and then `npm run build`. Building fails with the error "the command rm cannot be found". 

Other open source projects I'm aware of use the npm package rimraf for implementing deletion steps in a cross-platform manner.

### Versions
**fundamental-react:** Current master branch at the time of filing this issue

**Comment by jbadan** [comment]
Hi @huberv! Thank you for bringing this to our attention. Would you mind opening a pr?
