### ISSUE TITLE
component library is broken

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-react#130]
At the moment(after beta 7) the components(from the npm package) cannot be imported in a react app.

**Comment by aerfio** [comment]
At the moment to use npm package in https://github.com/kyma-project/console we had to:

1. Install fundamental-react
2. Install fiori-fundamentals
3. Install _@babel/runtime_
4. Go into node_modules/fundamental-react, npm i && npm run build

Only then it worked (imports from e.g 'fundamental-react/dist/Button/Button'), and there's still playground in this package

**Comment by droshev** [comment]
@aerfio could you test with the latest release?

**Comment by aerfio** [comment]
@droshev Now it works without babel plugin and without `npm i && npm run build` inside `node_modules` 👍. Only issue is that you still have to make explicit imports from `dist/component/component`
