### ISSUE TITLE
downgrade the version of webpack-dev-server to 3.1.9

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-react#137]
At the moment when a react app is created, it depends on `react-scripts` and its latest version 2.1.2 depends on webpack-dev-server@3.1.9.

**Comment by InnaAtanasova** [comment]
Downgrading the dependency caused potential security vulnerability. The recommended action is to upgrade to 3.1.11. All version <3.1.11 are considered vulnerable.

**Comment by droshev** [comment]
@InnaAtanasova you are right but we depend on react-scripts and it latest version 2.1.2 depends to webpack-dev-server to 3.1.9. Once react-script bumps the version of webpack-dev-server then we can revert that change.

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/168
