### ISSUE TITLE
Not able to use modules from react project.

### ISSUE THREAD

**Issue by rkcy** [SAP/fundamental-react#161]
I installed `fiori-fundamentals` and `fundamental-react` as mentioned in README.
I can see fundamental-react in `node_modules`, but it has only `dist` folder and not `lib`.

Now trying to create button as mentioned in documentation:
```
import { Button, ButtonGroup } from '/fundamental-react/src/';
```
It says that module '/fundamental-react/src/' not found.

Is there a sample project that can be referenced for using this library?

**Comment by CodesOfRa** [comment]
Hi @rkcy ,

we don't have a sample project, I will create an issue for this as i think we should have one :) but meanwhile  you can take a look at @droshev repo https://github.com/droshev/fd-react-helloworld .

Cheers
Ramona

**Comment by rkcy** [comment]
Thanks for the quick reply.  Since you you have already opened an issue for it, i am closing this one.

**Comment by jbadan** [comment]
Hi @rkcy! We recently changed the publish process and now publish a `dist` folder instead of `src`. The readme will be updated soon.
