### ISSUE TITLE
Add sample project to documentation

### ISSUE THREAD

**Issue by CodesOfRa** [SAP/fundamental-react#162]
I think we need to create a sample project as part of the documentation, importing the components sometimes is confusing .

**Comment by chrismanciero** [comment]
Should we rethink the folder structure of our components? Looking at this [article](https://hackernoon.com/creating-a-library-of-react-components-using-create-react-app-without-ejecting-d182df690c6b) it describes creating a /lib directory under the /src directory and putting all the components in there as well as an index.js file that exports all the components.  Would changing the folder structure help solve some of the issues users are having trying to import our components?

**Comment by CodesOfRa** [comment]
@chrismanciero no idea if the folder structure is the problem ( I need to do some reading 😃), but  I think will be easier to write 
``` js 
import {Button} from 'fundamental-react'
```  
than
```js
import {Button} from 'fundamental-react/dist/Button/Button'
```
 it also looks much cleaner 😄

**Comment by jiawang1** [comment]
you can have a look this [https://github.com/SAP/fundamental-react/issues/78#issuecomment-454006290](https://github.com/SAP/fundamental-react/issues/78#issuecomment-454006290), it just specify main/modlue field in package.json.

**Comment by alexanderchan** [comment]
@CodesOfRa agreed, I think something like palantir's blueprint shows us how it's done in a complex library:

```
import {
  Alignment,
  AnchorButton,
  Classes,
  Navbar,
  NavbarGroup,
  NavbarHeading,
  NavbarDivider
} from "@blueprintjs/core";
```

and similarly reactstrap
```
import { Alert } from 'reactstrap';
```

**Comment by alexanderchan** [comment]
The build pipeline and folder structure could be readily taken from something like [reactstrap](https://github.com/reactstrap/reactstrap/blob/master/package.json) .  They have umd, lib and esm builds and all the references for things like unpkg and cdns etc.  It's just going to work out better than an ejected create-react-app.
