### ISSUE TITLE
Update components to use arrow function syntax

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#171]
Since the repository is already using ES6, we can take advantage of the arrow function syntax.  When these are part of a React component, they will autobind removing the need for statements like this in the constructor:
```
this.updateDate = this.updateDate.bind(this);
```
Instead of writing component methods like:
```
updateDate(date) {
    ...
}
```
The functions can be written as such:
```
updateDate = (date) => {
    ...
}
```

**NOTE:** Standard React lifecycle functions do not need to be converted as React already handles the binding.

**NOTE:** There are likely some existing codemods that should make this easier.

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/172
