### ISSUE TITLE
Fix Import component on playground

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#239]
The `Import` component for the playground is showing imports as:
```
import { ActionBar } from '/fundamental-react/src/';
```
This is not correct or how a consumer would truly import the component.

Consider showing tree-shakable imports that import directly from the path in addition to named imports (like shown above).

**Comment by PierreFritsch** [comment]
@greg-a-smith for the time being until this is fixed, is there a way for consumers to use the components? 

In other words, how would I reference a component such as `ActionBar` from my app after doing `npm install --save fiori-fundamentals fundamental-react` and importing `../node_modules/fiori-fundamentals/scss/all.scss` in my App.scss file?

I tried with `import { ActionBar } from '../node_modules/fundamental-react/dist/';` but it doesn't seem to be the way to go:

![screenshot 2019-01-21 at 13 42 50](https://user-images.githubusercontent.com/10234267/51475563-05fe8b80-1d83-11e9-8456-59c350178288.png)

(My guess is that I'd have to wait for https://github.com/SAP/fundamental-react/issues/113 first, right? )

**Comment by CodesOfRa** [comment]
Hi @PierreFritsch 

I did a tiny sample app here : https://github.com/CodesOfRa/fundamental-react-demo

if you want to use a component you can use 
```javascript
import {Button} from 'fundamental-react/dist/Button/Button';
```

let me know if this is helping you.

**Comment by PierreFritsch** [comment]
Thanks @CodesOfRa - yes that helps!

From my point of view, it would make sense to include the contents of [your sample project's README](https://github.com/CodesOfRa/fundamental-react-demo) in the README file of this repository. That's exactly what I would expect as an external consumer under the section "Getting Started".

**Comment by CodesOfRa** [comment]
We are working on that, we have an issue open for this - to add some sample apps as part for documentation/Readme
