### ISSUE TITLE
fix remaining a11y eslint issues

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#245]
see commented out rules in https://github.com/SAP/fundamental-react/blob/master/.eslintrc

they are:

    #jsx-a11y/anchor-has-content: 2
    #jsx-a11y/anchor-is-valid: 2
    #jsx-a11y/aria-role: 2
    #jsx-a11y/click-events-have-key-events: 2
    #jsx-a11y/interactive-supports-focus: 2
    #jsx-a11y/no-noninteractive-element-interactions: 2
    #jsx-a11y/no-noninteractive-element-to-interactive-role: [2, { ul: ['tablist', 'menu']}]
    #jsx-a11y/no-onchange: 2
    #jsx-a11y/no-static-element-interactions: 2
    #jsx-a11y/role-supports-aria-props: 2

**Comment by jbadan** [comment]
Completed
