### ISSUE TITLE
Allow for customizable heading levels in components

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#249]
Currently, a number of components that use heading tags (_e.g._ `<h1>`, `<h2>`, etc.) have them hard-coded to use `<h1>`.  There should only be one `<h1>` element per page.  These components should take a prop to use the proper heading element (`<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>`).

Components include:
* `ActionBar`
* `MegaMenu`
* `Menu`
* `Modal`
* `Panel`
* `SideNavigation`

**Comment by bcullman** [comment]
I *think* fundamentals has their style coupled tight enough with the classname that changing out `<H1>` for `<HX>` will not effect the render of these. Still those examples should be updated to not encourage `<H1>` usage.

Created https://github.com/SAP/fundamental/issues/1178
