### ISSUE TITLE
Consider refactoring Shellbar into multiple components

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#266]
Currently, `Shellbar` is a very complex component and it's very difficult to unit test.  I think this should be refactored into multiple sub-components (`Profile`, `ProductSwitcher`, `Actions`, `Search` etc.) so each can have a concise API and thus be much more testable.  Then Shellbar can take these sub-components and construct the final markup.

**Comment by AdamFedor** [comment]
CORUI-6126 for our side of the work.

**Comment by arminnaimi** [comment]
@greg-a-smith I think this seems to be modelled after the SAPUI5 control that I got to work with just yesterday. Is this project following similar composition choices to SAPUI5?
