### ISSUE TITLE
Package documentation on npmjs.org: Clarify how to import the fiori-fundamentals SCSS file

### ISSUE THREAD

**Issue by PierreFritsch** [SAP/fundamental-react#267]
When I use [create-react-app](https://github.com/facebook/create-react-app) to create a new React app - which is the way how apps are created in the [React tutorial](https://reactjs.org/tutorial/tutorial.html):

    npx create-react-app my-app
    cd my-app
    npm start

and I install `fundamentals-react` according to [its documentation on npmjs.com](https://www.npmjs.com/package/fundamental-react)

    npm install --save fiori-fundamentals # fiori-fundamentals@1.4.1
    npm install --save fundamental-react # fundamental-react@0.0.14

and I include the Fiori Fundamentals CSS in my React application by including the following lines at the top of the file `src/App.css` as stated on [the package page](https://www.npmjs.com/package/fundamental-react):

    $fd-icons-path: "~fiori-fundamentals/scss/icons/";
    $fd-fonts-path: "~fiori-fundamentals/scss/fonts/";
    @import '../node_modules/fiori-fundamentals/scss/all.scss';

then I get an error in my browser (Chrome version 71.0): 

![screenshot 2019-01-21 at 10 54 01](https://user-images.githubusercontent.com/10234267/51466648-f83d0c00-1d6a-11e9-8881-56386eb9273b.png)

I'm playing the React.js rookie by following the documentation, please excuse me if this issue is trivial to solve...

**Comment by PierreFritsch** [comment]
It seems that mixing css and scss is not a good idea...

Renaming the file `src/App.css` to `src/App.scss` in the project generated by `create-react-app` did the trick for me. 

I'd suggest to update the documentation on https://www.npmjs.com/package/fundamental-react so that other rookies won't stumble here: Replace "In your App.css or App.scss file" with "In your App.scss file".

![screenshot 2019-01-21 at 12 59 34](https://user-images.githubusercontent.com/10234267/51473506-da78a280-1d7c-11e9-861e-8ee315102f29.png)

By the way, shouldn't the sentence below the code sample read "browse the components currently available with Fundamental React" instead of "Fundamental Vue"?

**Comment by nhebling** [comment]
Hi,

I faced the same issue and got it solved in the meantime - but I'm now having trouble importing and using the different components as the documentation is also not covering this part.

On top of the any component-documentation it says e.g. `"import { ActionBar } from '/fundamental-react/src/';"` but there is no _"src"_ directory if you import it via NPM.
For my App.js, I have to go one directory-level up to find the "_node_modules_", so I've tried different approaches:

```
import { ActionBar } from '../node_modules/fundamental-react'
import { ActionBar } from '../node_modules/fundamental-react/dist'
import '../node_modules/fundamental-react/dist';
import * from '../node_modules/fundamental-react/dist';
```

Nothing worked so far, also I noticed that the index.js in the "_dist_" directory points to "_../src/....._" - but there is no "_src_" directory if you install it via NPM

Would be very nice to have the documentation fixed.

**Comment by CodesOfRa** [comment]
hi @nhebling ,

I did a very tiny sample app for fundamental-react : https://github.com/CodesOfRa/fundamental-react-demo

You can check this one until we fix the documentation.

Let me know if it helps.

**Comment by droshev** [comment]
@jbadan i guess this issue has been fixed by #271, right?
do we have to do anything else(beside pushing it to npm)? :)

**Comment by jbadan** [comment]
@droshev yeah! I'll close this once the fix gets to npm.

**Comment by jbadan** [comment]
npm is updated to v0.1.0
