### ISSUE TITLE
Add missing functionality to SearchInput

### ISSUE THREAD

**Issue by aerfio** [SAP/fundamental-react#279]
Right now we have no access to `event` in `onChange` prop.
https://github.com/SAP/fundamental-react/blob/370325509cfea75d5277b96fe99dbe982e444158/src/SearchInput/SearchInput.js#L37
If you just changed this line to `this.props.onChange(event)` it would work 👍

**Comment by CodesOfRa** [comment]
@aerfio Would you like to create a PR for this 😄 ?

**Comment by chrismanciero** [comment]
@aerfio Do you want the actual event or just the search value (event.target.value) that is entered?

**Comment by aerfio** [comment]
@CodesOfRa done, look at #281 👍

**Comment by CodesOfRa** [comment]
@aerfio Thanks for contributing !🌟
