### ISSUE TITLE
Improve Docs: Add preamble pages (Home / Installation / Usage)

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental-react#298]
Description

Follow design seen here:
https://sap.github.io/fundamental-ngx/docs/home

![image](https://user-images.githubusercontent.com/5056972/51769845-eb852480-2098-11e9-9d7d-66a66aa106ce.png)

CORUI-6167

**Comment by christinec01** [comment]
Hey there! Curious how you were able to get your storybook powered app to default to loading the docs page rather than canvas.

**Comment by jbadan** [comment]
@christinec01 
Using `--docs` argument for `storybook-static` will have this affect. It's undocumented in storybook and subject to change though! https://github.com/SAP/fundamental-react/blob/master/package.json#L38

**Comment by christinec01** [comment]
Thanks @jbadan ! 
I did come across the `--docs` flag, but it seems to altogether hide the 'canvas' and 'docs' tabs as well, which isn't desired; did you find this to be the case? (sorry if I'm missing something obvious!)

**Comment by jbadan** [comment]
@christinec01 No problem! We wanted to hide the tabs on our published website (only showing what would have been in docs), only showing the tabs in dev mode. I'm not sure how to accomplish what you want, but I believe there are some issues about it in the storybook repo.
