### ISSUE TITLE
enhancement: Have you consider animated result?

### ISSUE THREAD

**Issue by suncodeer** [SAP/fundamental-react#311]
### Description
Currently I am working on sap labs in the China.
Recently I want to use this fundamental-react to create one finance app.
Then I can compare this app with smart template app. But I can't find core team of smart template.
Do you have any contact information?

Could I get some support from your side ? If I make it happen, in the future I will get much more official support from team manager.

Also in the meantime, in the real project many good things will be found.
Looking forward to your reply

### Versions
**fundamental-react:**
**fiori-fundamentals:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by droshev** [comment]
@suncodeer maybe you can join our slack space(check in the readme) and there we can discuss more what you are trying to implement?
