### ISSUE TITLE
Tabs component not suitable for use

### ISSUE THREAD

**Issue by magicmatatjahu** [SAP/fundamental-react#315]
### Description

At the moment `Tabs` component not suitable for use (for dev and prod) -> see the attachment. 
**Hint from me**: remove react-router dependency from this component and change code to something like this: 
https://github.com/kyma-project/console/blob/master/components/react/src/components/Tabs/index.js

If you want, I can create PR with fix (and/or new architecture of component) to Sunday.

### Versions
**fundamental-react:** 0.3.0-rc.0
**fiori-fundamentals:** 1.4.1

---

_**NOTE:** Where applicable, please include uncropped screen captures._

![image](https://user-images.githubusercontent.com/20404945/51899414-3cf02500-23b3-11e9-9252-bc57d8b543f7.png)

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jeffredodd** [comment]
There is an upcoming change related to #115 that will improve the Tab API and separate its dependecy on React Router.

**Comment by magicmatatjahu** [comment]
@jeffcollier Thank you for you comment! In what form will the new api be and when will it be realized? I do not hide that tabs are needed in my project. If I created PR with a new tabs architecture, would you mind?

**Comment by jeffredodd** [comment]
This is resolved by #336. See #344 for issues with sizing.
