### ISSUE TITLE
Components need static display names

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-react#339]
### Description

Each component needs a set display name for easier debugging when minified. When display names are not set, the component "names" become "t", "o", "c", etc.  See: https://github.com/facebook/react/issues/4915

ex: 
`static displayName = 'Button';`

alternatively, we could expect consumers to use https://www.npmjs.com/package/babel-plugin-add-react-static-displayname if they want this feature.

### Versions
**fundamental-react:** current
**fiori-fundamentals:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by mobot11** [comment]
Is this something we want to control? We provide the library in a non-minified state I feel like we should leave it up to the consumer to decide what their minified bundle output looks like. Or at least give them the option to include it somehow as I'm guessing it slightly increases bundle size.

**Comment by jbadan** [comment]
In my opinion, it's definitely something we want to control. It makes debugging a pain without it and is done by all the other major libraries.

**Comment by mobot11** [comment]
Sounds good to me. I'm willing to spare a few bytes for our own sanity 😄
