### ISSUE TITLE
Tabs shift in size when content changes

### ISSUE THREAD

**Issue by jeffredodd** [SAP/fundamental-react#344]
### Description
When changing through tabs, they shift in sidesize. 
![screen shot 2019-02-01 at 9 49 03 am](https://user-images.githubusercontent.com/2861516/52140377-7c16b400-2607-11e9-8972-0c7f40ec7d32.png)
![screen shot 2019-02-01 at 9 48 58 am](https://user-images.githubusercontent.com/2861516/52140378-7c16b400-2607-11e9-983a-c9c5fa868dbb.png)

While on Fundamentals they do not. https://sap.github.io/fundamental/components/tabs.html
![screen shot 2019-02-01 at 9 54 06 am](https://user-images.githubusercontent.com/2861516/52140674-35758980-2608-11e9-9761-bc30e807425d.png)
![screen shot 2019-02-01 at 9 54 03 am](https://user-images.githubusercontent.com/2861516/52140675-35758980-2608-11e9-8a8c-3f629a489141.png)

Most likely this can be fixed by locating the tab content outside of the `Tab`'s `<ul>` component.

**Comment by chrismanciero** [comment]
There are a couple of problems with the Tabs Component implementation.
1) The `<li>` element for each tab is getting a 'is-selected' class applied when the tab is selected. This should be removed and a value of aria-selected="true" should be added to the selected <a>
2) The `<a>` elements should have `role=tab` attribute added
3) The content of the tabs are being inserted into the `<li>` element (at the same level as the `<a>`). The implementation on the Fundamental page has the content for the tabs being added after the tab list. (First tab content highlighted in blue)
![screen shot 2019-02-11 at 1 52 28 pm](https://user-images.githubusercontent.com/38330612/52585992-5312d200-2e04-11e9-870a-886f9067a59b.png)
The content corresponding to the selected tab should have the following attribute set `aria-expanded="true"`

**Comment by bcullman** [comment]
The preferred HTML layout for this is seen here (and elsewhere): https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

```
<nav>
    <ol>
        <li><a href="">Link 1</a></li>
        <li><a href="">Link 1</a></li>
        <li>Text one</li>
    </ol>
</nav>
```

**Comment by chrismanciero** [comment]
Why would we want 2 ways to implement a tab list?(https://sap.github.io/fundamental/components/tabs.html)

One implementation is using `<ul>` and `<li>` and the other is using `<nav>` and `<span>`. Is there a preferred way to implement a tab list?

As a test, if I went with a mix of the approaches (see @bcullman comment ⬆️ ) the tab list loses the bottom padding.

Using `<ul> and <li>`:

![screen shot 2019-02-14 at 3 07 20 pm](https://user-images.githubusercontent.com/38330612/52814500-4f808480-306a-11e9-9df7-c74a9e520964.png)

Using `<nav>, <ol> and <li>`:

![screen shot 2019-02-14 at 3 07 40 pm](https://user-images.githubusercontent.com/38330612/52814517-5909ec80-306a-11e9-80e6-d0ab287d4dc0.png)
