### ISSUE TITLE
Documentation Styles: SideNav Group Title is overridden by local styles. 

### ISSUE THREAD

**Issue by jeffredodd** [SAP/fundamental-react#354]
### Description
SideNav's `H1` element is altered by the documentation style. 
https://github.com/SAP/fundamental-
react/blob/a16eb5c89623e209b311f4ad9a5f01cd7f38ee2e/src/_playground/App.scss#L81

#### Actal (Master)
<img width="273" alt="screen shot 2019-02-04 at 8 54 43 pm" src="https://user-images.githubusercontent.com/2861516/52253988-f1141300-28bf-11e9-9e73-18f08a2c6b9e.png">

#### Expected (Latest Release)
<img width="265" alt="screen shot 2019-02-04 at 8 54 52 pm" src="https://user-images.githubusercontent.com/2861516/52253990-f40f0380-28bf-11e9-87d1-24b25647e9b0.png">

### Versions
**fundamental-react:** 0.3.2
**fiori-fundamentals:** 1.4.0

**Comment by jbadan** [comment]
Oops - my bad. Here's a working link: https://github.com/SAP/fundamental-react/blob/master/src/_playground/App.scss#L81
