### ISSUE TITLE
Dropdown Component: isContextual prop missing

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-react#360]
### Description

The prop `isContextual` is used several times in the playground for the Dropdown component. The Dropdown component does not have an `isContextual` prop. 

https://github.com/SAP/fundamental-react/blob/master/src/Dropdown/Dropdown.js#L5

https://github.com/SAP/fundamental-react/blob/master/src/_playground/documentation/Playground/Playground.js#L383

What was this prop meant to do? 
### Versions
**fundamental-react:** 0.3.1
**fiori-fundamentals:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by chrismanciero** [comment]
You can see from this [PR](https://github.com/SAP/fundamental-react/commit/3cfc0f4326303876fefa024feac4034257a078b9#diff-acc3a01ef84560b7b72c24ff5650dbf0) the **isContextual** property was removed when the component was refactored. It probably was missed in the Playground.js file.
