### ISSUE TITLE
searchInput should be rebuilt as an InputGroup

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental-react#389]
### Description
The search input component should be rebuilt as an InputGroup. Additionally, it might also be considered a pattern, vs a full blown component.

### Versions
**fundamental-react:** 0.3.2
**fiori-fundamentals:** ^1.4.0

**Comment by chrismanciero** [comment]
We should probably get some clarification from the design team on the correct look and feel for the Search Input. Right now there are 2 different user experiences.

1) An example from the [Input Group](https://sap.github.io/fundamental/components/input-group.html) page has the search icon before the text field and the icon not clickable.
![screen shot 2019-02-11 at 11 59 38 am](https://user-images.githubusercontent.com/38330612/52579723-bf85d500-2df4-11e9-8389-8a8ac1086d40.png)

2) An example of the [Search Input](https://sap.github.io/fundamental/components/search-input.html) component has the search icon after the text field and the search icon is a clickable button.
![screen shot 2019-02-11 at 11 59 50 am](https://user-images.githubusercontent.com/38330612/52579762-d4faff00-2df4-11e9-83ea-96f234968cf3.png)
