### ISSUE TITLE
Internal Props not be required to be documented

### ISSUE THREAD

**Issue by jeffredodd** [SAP/fundamental-react#393]
### Description
internal props have linting rules which require them to be documented which can lead to confusing documentation full of props consumers should not consume. 

We should aim to create an option to suppress internal props within our documentation. This would allow internal props to use `propTypes` but would be skipped in the documentation.

**Comment by jbadan** [comment]
https://github.com/storybookjs/storybook/pull/8868/files

**Comment by jeffredodd** [comment]
Oh yay yeah you guys should do this 😉
