### ISSUE TITLE
Errors when inserting React node inside the paragraph tag in Tab component

### ISSUE THREAD

**Issue by Aleks239** [SAP/fundamental-react#401]
Hello,

I noticed that the current Tab component implementation renders the _p_ tag with the text after selecting a tag. However, in the docs the **content** prop has the type of React node. It means when I use the React node as a content rendered when Tab is clicked, it gives the errors in the console. (It happens because I may insert the _div_ inside the _p_ tag which is rendered by the framework)
<img width="982" alt="screenshot 2019-02-13 at 11 28 32" src="https://user-images.githubusercontent.com/6854546/52701287-8da27900-2f82-11e9-8d42-17f24f560042.png">

What is the point of having **react node** type on the **content** prop?

Best regards,

Aleksandr

**Comment by greg-a-smith** [comment]
Hi @Aleks239.  Thanks for reporting the issue.  The `TabGroup` and `Tab` components definitely need an overhaul.  There is also another issue with tabs (#344) which should be addressed at the same time.  We will put together a story to get these issues addressed.

**Comment by jbadan** [comment]
Fixed by #414
