### ISSUE TITLE
Cannot access component documentation pages

### ISSUE THREAD

**Issue by cellio365** [SAP/fundamental-react#406]
### Description
I cannot access documentation pages except their home.
e.g., I get 404 to access actionBar component page:
https://sap.github.io/fundamental-react/actionBar

### Versions
**fundamental-react:**
**fiori-fundamentals:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by bcullman** [comment]
Looks like we hit this on 0.3.3 release. We are investigating...

**Comment by bcullman** [comment]
this will be fixed by #407. 

unfortunately, we are blocked because coveralls is not returning coverage status. We are now looking in to that.
