### ISSUE TITLE
Docs are broken in IE 11

### ISSUE THREAD

**Issue by mobot11** [SAP/fundamental-react#409]
### Description
https://sap.github.io/fundamental-react/home doesn't load in IE 11. Looks like Object.Assign isn't being polyfilled correctly.

![ie-11-docs](https://user-images.githubusercontent.com/9958488/52810017-74fb9700-3046-11e9-8c11-8b793bea5670.png)

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/742
