### ISSUE TITLE
Consider switching from coveralls to https://codecov.io/ for tracking code coverage

### ISSUE THREAD

**Issue by mobot11** [SAP/fundamental-react#416]
### Description
Coveralls is slow and error prone. We already had to remove the GitHub integration due to performance issues and now are running into issues with the build failing on Travis. https://codecov.io/ is a similar tool and also free for open source repos.

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
coveralls got better! 🎉
