### ISSUE TITLE
Move FormGroup to Forms directory

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#427]
### Description
The `FormGroup` component is currently in the `InputGroup` directory and thus shows up in the docs under the "Input Group" nav link, which makes no sense.  Sure, input groups can be used inside form groups, but they are not specifically related.  The `FormGroup` component should be in the `Forms` directory.

### Versions
**fundamental-react:** Any
**fiori-fundamentals:** Any

**Comment by jbadan** [comment]
Please remember to preserve git history following this guide: https://github.com/SAP/fundamental-react/wiki/One-Component-Per-File#how-to-preserve-git-history

**Comment by jbadan** [comment]
Like #429, in order for history to be preserved, we will need to turn off squash and merge. We should test this in a test repo, like deployment-lab, to make sure this doesn't increment the rc version for every commit as it's not squashed. I think travis will take care of only incrementing once based on cancelling the other builds.

**Comment by jbadan** [comment]
closed by https://github.com/SAP/fundamental-react/pull/769
