### ISSUE TITLE
Split unit tests fo components in separate tests for each component

### ISSUE THREAD

**Issue by greg-a-smith** [SAP/fundamental-react#429]
### Description
With the refactoring of components into separate files, there should be a `*.test.js` file for each as well.  Created this as a separate story since it will likely involve writing or rewriting a number of tests to actually have them test individual components.

Components:
- ActionBar
- Button
- Forms
- ListGroup
- Panel
- SideNav
- Tile
- Time
- TimePicker
- TreeView

### Versions
**fundamental-react:** Any
**fiori-fundamentals:** Any

**Comment by jbadan** [comment]
When addressing this issue, be sure to save git history: https://github.com/SAP/fundamental-react/wiki/One-Component-Per-File#how-to-preserve-git-history

**Comment by jbadan** [comment]
In order for history to be preserved, we will need to turn off squash and merge. We should test this in a test repo, like deployment-lab, to make sure this doesn't increment the rc version for every commit as it's not squashed. I _think_ travis will take care of only incrementing once based on cancelling the other builds.
