### ISSUE TITLE
Tables are bigger than parent container

### ISSUE THREAD

**Issue by akucharska** [SAP/fundamental-react#466]
### Description
Right now tables are not responsive. They tend to overflow container they are placed in. It is a problem on mobile devices.

You should make sure the table is never bigger than parent container. Maybe some option like `table-layout: fixed;`,  'word-break' or 'text-overflow: ellipsis;'?

### Versions
**fundamental-react: 0.4.0**
**fiori-fundamentals: 1.4.3**

**
![Screenshot 2019-03-11 at 14 18 18](https://user-images.githubusercontent.com/20790348/54126739-8dbe5900-4408-11e9-895a-cbac0cacd3ee.png)
---

**Comment by hertweckhr1** [comment]
Still issue for tables

**Comment by greg-a-smith** [comment]
@akucharska Although there are some minor style tricks that could help by wrapping text or showing ellipsis, there are still going to be instances when tables will have more data and/or columns that can be displayed within a horizontal space.  A better "fix" for this is simply to wrap the table in a `<div>` with `overflow: auto` set.  This will keep the table and its contents intact yet allow users to scroll horizontally to see additional columns.
