### ISSUE TITLE
Publish ES Modules directory along with CommonJS

### ISSUE THREAD

**Issue by mobot11** [SAP/fundamental-react#510]
### Description
We should publish ES Modules so consumers can take full advantage of tree shaking if they so choose.

### Versions
**fundamental-react: 0.5.1-rc.18

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by henrikyt** [comment]
+1

Some of the components don't render at all when imported, but work just fine when the source code is copied and passed through our webpack+babel. 
I'm not exactly sure what in our configuration causes it. Maybe the fundamental component bundles have some needed stuff that webpack removes/mangles.
I would really appreciate es modules, so we could have more control over what goes inside our release.

**Comment by jbadan** [comment]
tangentially related to https://github.com/SAP/fundamental-react/pull/772
