### ISSUE TITLE
Shellbar causes multiple React keys warnings

### ISSUE THREAD

**Issue by maylukas** [SAP/fundamental-react#512]
### Description
When using the Shellbar component, multiple errors come up in the console.

Upon mount:
```
Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div
    in div
    in div (created by SearchInput)
    in SearchInput
    in div
    in div
    in div
    in div
    in Shellbar
...
```
Upon click on the user menu:
```
Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in Menu.Item
    in ul (created by Menu.List)
    in Menu.List
    in nav (created by Menu)
    in Menu
    in div (created by InnerPopper)
    in InnerPopper (created by Context.Consumer)
    in Popper
    in span (created by Foco)
    in Foco
    in Manager
    in Popper
    in Popover
    in div
    in div
    in div
    in div
    in div
    in Shellbar 
...
```

The mounted shellbar has a search input as well as a user menu. 

### Versions
**fundamental-react:** 0.5.0
**fiori-fundamentals:** 1.5.1
**react**: 16.8.1

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by LucaFilitz** [comment]
The bug is still present in the following versions:
fundamental-react: 0.6.1
fundamental-styles: 0.1.0
react: 16.8.6

**Comment by parostatkiem** [comment]
It's also present in `<Menu.Item>` - you can't pass `key` prop to it.

**Comment by sjanota** [comment]
I did a little digging while working on #739 and found out that there's something wrong with the compiled version of the fundamental-react. When I copy the source and allow webpack do the job everything works fine. But when I use components from npm package the error reappears. Maybe that helps somehow to narrow down the issue.

**Comment by sjanota** [comment]
I narrowed it down to '@babel/plugin-transform-react-inline-elements'. It seems like it should only be used in final application, not in libraries. Here's a PR to remove it: https://github.com/SAP/fundamental-react/pull/741.
