### ISSUE TITLE
Tabs component does not accept null as child

### ISSUE THREAD

**Issue by aerfio** [SAP/fundamental-react#514]
### Description

![image](https://user-images.githubusercontent.com/17271979/56117889-64de3600-5f69-11e9-84d9-4654a260970c.png)
![image](https://user-images.githubusercontent.com/17271979/56117905-70c9f800-5f69-11e9-9165-175e6e6aa10e.png)

`Tabs` component doesn't accept null as child, leading to crash as shown in screenshots above.

### Versions
**fundamental-react:** 0.5
**fiori-fundamentals:** 1.5.3

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by greg-a-smith** [comment]
Hi @aerfio.  I'm curious of the use case of _why_ this would be needed.  It seems pretty legitimate to have the consumer own filtering out the child objects being passed.  Generally speaking, these components are supposed to be pretty "dumb" and should leave most of the control in the hands of the consumers.

**Comment by aerfio** [comment]
@greg-a-smith Hi! `null` is perfectly valid value returned by react component, so it should be handled - components should be dump but not so dumb that they lack basic features that 

Besides, implementation that is now prevents us from writing such a code:
![image](https://user-images.githubusercontent.com/17271979/56378582-c9212400-620d-11e9-93c3-232f186d1705.png)
Both of those basic cases fail and cause app to crash.

We could theoretically put those `<Tab/>` component in array and filter falsy values, but it would be weird and ugly.

Lemme know if you guys have different opinion, or if I just missed some kind of thing 😛

**Comment by greg-a-smith** [comment]
@aerfio Although you are correct that the ternary operation won't be supported, there's a cleaner way of writing it.  It's essentially the line above although `falseCondition` would change to `trueCondition`.
```jsx
render() {
    return (
        <TabGroup>
            <Tab title='One'>Will always show</Tab>
            {trueCondition && <Tab title='Two'>Will only show when condition is true</Tab>}
        </TabGroup>
    );
}
```

**Comment by aerfio** [comment]
@greg-a-smith Nope, that's why I presented you both of those cases, I just checked that to be sure.

And I wrote `falseCondition` to indicate that this variable is falsy, not that you should write `false && <Component/>`

To be more precise: `condition && <Tab/>` and `condition ? <Tab/> : null` <- they both crash app if `condition` is falsy, and they shouldn't, because that's how you typically do this in React apps imho

**Comment by greg-a-smith** [comment]
@aerfio I see that now.  Hmmmm.  Well, that's unfortunate that the `trueCondition && <Component/>` syntax passes a null as one of the children.  We will keep this issue open and look at the PR that's been created to fix this.
