### ISSUE TITLE
width of menu list is not matched with input box in component ComboboxInput

### ISSUE THREAD

**Issue by jiawang1** [SAP/fundamental-react#531]
### Description
when show the menu list of ComboboxInput, the width 100% of menu is lost since it is rendered in portal.

### Versions
**fundamental-react:** : 0.51
**fiori-fundamentals:**

**Comment by ChristianKienle** [comment]
Maybe you find this Popper modifier useful:

https://github.com/ChristianKienle/k-pop/blob/master/src/Pop/k-pop.vue#L212-L232

More Info: https://christiankienle.github.io/k-pop/examples/#body-size-modes

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/890
