### ISSUE TITLE
Documentation does not contain fundamental-react URI 

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-react#54]
Following the documentation in the readme takes you to this URL: https://sap.github.io/fundamental-react/

Navigating to a component's detail page (such as the action bar) will result in a URL like so: https://sap.github.io/actionBar

The URL should be https://sap.github.io/fundamental-react/actionBar

Also, navigating directly to the component's URL through the browser input results in a 404 - component details must be navigated to via the side nav

**Comment by InnaAtanasova** [comment]
The issue is now fixed.
