### ISSUE TITLE
Need to create disable edge detection prop for Popover

### ISSUE THREAD

**Issue by hertweckhr1** [SAP/fundamental-react#540]
### Description
When popover is longer than screen size it automatically changes the orientation from bottom to top.  Consumer wants to disable edge detection, but there is currently not a prop to do so. 

Need to create a prop that allows consumers to disable edge detection on popover.js. Will need to pass this prop from popper.js to our popover component. 

### Versions
**fundamental-react:** 0.5.1

**Comment by aerfio** [comment]
Affects us as well 😢 https://github.com/kyma-project/console/issues/785
