### ISSUE TITLE
Cannot find the declaration module

### ISSUE THREAD

**Issue by JihunKang1** [SAP/fundamental-react#549]
### Description

While I put the following import codes in a file, it looks like there is no declaration module for a component. 
`import { Shellbar } from 'fundamental-react/lib/Shellbar';`
Above code snippet throws following message.
`Could not find a declaration file for module 'fundamental-react/lib/Shellbar'. '/Users/i333130/src/cnr-app1/node_modules/fundamental-react/lib/Shellbar/index.js' implicitly has an 'any' type.
  Try 'npm install @types/fundamental-react' if it exists or add a new declaration (.d.ts) file containing 'declare module 'fundamental-react/lib/Shellbar';ts(7016)`

### Versions
**fundamental-react: 0.5.3**
**fiori-fundamentals: 1.5.8**

**Comment by jbadan** [comment]
Hi Jihun, we do not currently have typescript support. See this stackoverflow article on how to fix this error in your app: https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

Feel free to reopen the issue if there is something else missing.

**Comment by JihunKang1** [comment]
Hi Jenna, thanks for explanation. I am working on adding the definition modules, and works well with some controls. If you don't mind, can I contribute this change?

**Comment by JihunKang1** [comment]
Hi Jenna,

Installing additional dependency, @types/fundamental-react, fixes this error in our app. Thanks.
