### ISSUE TITLE
Tree: expand collapse not working with functional components

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-react#646]
### Versions
**fundamental-react:** 0.6.1

The props `onExpandClick`, `expandData` and `isExpanded` are not being passed properly down through `DetailTree`.  I believe this has to do with our `React.cloneElement` functions, we might need to add something recursive in there. 

https://github.com/SAP/fundamental-react/blob/master/src/TreeView/TreeView.js#L120

`child` here is empty if using a pass through component.

Not working: 
```
const DetailTree = () => (
     <TreeView.Item>						
          <TreeView.Row>
                    <TreeView.Col>Row added through a custom Component: expand collapse- not w</TreeView.Col>
          </TreeView.Row>	

          <TreeView.Branch>							
               <TreeView.Item>							  
                    <TreeView.Row>
                         <TreeView.Col>Generated Child</TreeView.Col>
                    </TreeView.Row>                                
               </TreeView.Item>							  
          </TreeView.Branch>	

     </TreeView.Item>                    
)

class TreeNotWorking extends React.Component {
     
     render() {
          return (
               <TreeView>                
                    <TreeView.Tree>                       
                    <DetailTree />  
                    </TreeView.Tree>
               </TreeView>
          );
     }     
}

export default TreeNotWorking;
```

Working: 
```
class TreeWorking extends React.Component {
     
render() {
    return (
        <TreeView>                
            <TreeView.Tree> 
                <TreeView.Item>	                         
                        <TreeView.Row>
                            <TreeView.Col>Row added directly in render</TreeView.Col>
                        </TreeView.Row>	

                        <TreeView.Branch>							
                            <TreeView.Item>							  
                                <TreeView.Row>
                                    <TreeView.Col>Hardcoded row child</TreeView.Col>
                                </TreeView.Row>                                
                            </TreeView.Item>							  
                        </TreeView.Branch>
                </TreeView.Item> 
            </TreeView.Tree>
        </TreeView>  
        );
    }
}

export default TreeWorking;
```

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by tnurmi82** [comment]
I can confirm this bug. Expand & collapse work fine for a static/hardoded <TreeView.Branch> inside a Functional Component, but won't work if Branches are dynamically created. Hoping to see some activity on this issue.

**Comment by jbadan** [comment]
@tnurmi82 We're open to outside contributions if you're interested!

**Comment by tnurmi82** [comment]
@jbadan I only just very recently started learning React, so I don't think I'd be able to solve this just yet :) I don't suppose this bug could be fixed within the next few days? Unfortunately I have a tight schedule with my first React SPA...
