### ISSUE TITLE
Bug: Dropdown items not working when inside a Modal

### ISSUE THREAD

**Issue by adrilb** [SAP/fundamental-react#649]
### Description
When a Dropdown component is inside a Modal component, onClick events are not triggered when a Menu.Item component is clicked.

### Versions
**fundamental-react:** 0.6.1
**fundamental-styles:** 0.1.0

**Comment by dariadomagala** [comment]
I have the same problem now, what is the status of this bug?

**Comment by kwiatekus** [comment]
Same here.. regardless if the Menu.Items are wrapped by ComboboxInput or Popover.

**Comment by jbadan** [comment]
closed by https://github.com/SAP/fundamental-react/pull/764
