### ISSUE TITLE
Tile component writes productTile prop as invalid attribute in DOM Element

### ISSUE THREAD

**Issue by xppalmeida** [SAP/fundamental-react#750]
### Description

When using Tile.Media component, it is generating an invalid HTML attribute: `productTile`. This is the console warning message:

> Warning: React does not recognize the `productTile` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `producttile` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Tile.Media)
    ...etc

Checking the [_TileMedia.js file](https://github.com/SAP/fundamental-react/blob/master/src/Tile/Tile.js#L44) and [here](https://github.com/SAP/fundamental-react/blob/master/src/Tile/_TileMedia.js#L6), it should not happen, since `productTile` is being previously destructured apart from the `...rest` params. But somehow it is.

This is an example from where we get that `productTile` error:

```jsx
<div className={styles.userDetails_header}>
  <Tile className={styles.userDetails_header__fd_tile}>
    <Tile.Media className={styles.userDetails_header__fd_tile__media}>
      {userProfile.avatar ? (
        <Image
          aria-label="TILE_MEDIA_ALT"
          photo={userProfile.avatar}
          size="l"
          type="circle"
        />
      ) : (
          <Icon glyph="person-placeholder" size="xl" />
        )}
    </Tile.Media>
    <Tile.Content title={userProfile.name}>
      <p>{userProfile.role}</p>
    </Tile.Content>
  </Tile>
</div>
```

### Versions
**fundamental-react:** 
0.6.1
**fundamental-styles:**
0.1.0

![Screenshot 2019-09-27 at 10 44 29](https://user-images.githubusercontent.com/52708845/65759879-da9f1e00-e113-11e9-8182-5991b158823a.png)

**Comment by jbadan** [comment]
was fixed in #742, you will need to upgrade to 0.7.0 when we release it very soon or start using the rc version.
