### ISSUE TITLE
enhancement: anchor and icon restructuring

### ISSUE THREAD

**Issue by stefanoScalzo** [SAP/fundamental-react#763]
### Description
Currently when applying overflow:hidden, the hover and focus will go on either the icon or on the anchor item but not both! Therefore to do both add the span element within the anchor.

### Versions
**fundamental-react:**
**fundamental-styles:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

![](https://user-images.githubusercontent.com/50607147/66221525-2b2af400-e69d-11e9-820a-71be0ed17706.png)

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
https://github.com/SAP/fundamental-styles/pull/364

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/890
