### ISSUE TITLE
Popover is always stretched to the right edge of the viewport

### ISSUE THREAD

**Issue by parostatkiem** [SAP/fundamental-react#788]
### Description
This happens on the documentation website as well as in my application that uses Fundamental-react.
![image](https://user-images.githubusercontent.com/22825433/68195719-9d9e3500-ffb7-11e9-86e6-ec41e6e12a95.png)

### Versions
**fundamental-react:** current
**fundamental-styles:** none

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
closed by #798
