### ISSUE TITLE
Feature Request: Loading Spinner

### ISSUE THREAD

**Issue by JaySardhara** [SAP/fundamental-react#797]
Can we have loading spinner or spinners component?
Based on https://sap.github.io/fundamental-styles/components/loading-spinner.html 
### Versions
**fundamental-react:** 0.7.1
**fundamental-styles:** 0.3.0

**Comment by droshev** [comment]
@JaySardhara the spinners had been deprecated. The new component is [busy indicator](https://fundamental-styles.netlify.com/components/busy-indicator.html)

**Comment by JaySardhara** [comment]
@droshev thanks for update. I suspect that is planned for future release in fundamental-react?

**Comment by jbadan** [comment]
Closing in favor of #879
