### ISSUE TITLE
Modal does not honor provided CSS class in "className" property

### ISSUE THREAD

**Issue by JaySardhara** [SAP/fundamental-react#800]
### Description
CSS class provided in Modal "className" property does not have any effect.

Currently bypassing this issue by directly manipulating underlying "fundamental-style" CSS property of Modal.

`.fd-modal{
    max-width: none!important;
}
.modal-demo-bg{
    width: 90%;
}`

### Versions
**fundamental-react:** 0.7.1
**fundamental-styles:** 0.3.0

**Comment by jbadan** [comment]
Hi @JaySardhara - the class is being spread to the outermost div. https://github.com/SAP/fundamental-react/blob/master/src/Modal/Modal.js#L67

**Comment by JaySardhara** [comment]
@jbadan I might be missing something, but shouldn't that class be applied to Modal component instead?

**Comment by jbadan** [comment]
Probably, I was just letting you know why it wasn't working like you expected. Feel free to open a pr!

**Comment by Wawrzyn321** [comment]
Here we go with [PR](https://github.com/SAP/fundamental-react/pull/816).
