### ISSUE TITLE
Unable to use nogap and disableStyles props on LayoutGrid component

### ISSUE THREAD

**Issue by Braiden-Psiuk** [SAP/fundamental-react#802]
### Description
I'm unable to use the **nogap** and **disableStyles** props when using LayoutGrid components.
After inspecting the source files it looks like these props were removed, but they are still included in the [component overview docs.](https://sap.github.io/fundamental-react/layout-grid) Not sure these props were purposefully removed and no longer supported.

### Versions
**fundamental-react:** 0.7.1 (@latest as of the date of this post)
**fundamental-styles:** 0.3.0 (@latest as of the date of this post)

**Comment by jbadan** [comment]
Hi @Braiden-Psiuk! I fixed the typo so `no-gap` will work as expected, but can you clarify what you mean by `disableStyles` is not working? `no-gap` and `disableStyles` will not work together as `no-gap` is adding a classname, but `disableStyles` is removing all css.

![Screen Shot 2019-11-22 at 2 51 40 PM](https://user-images.githubusercontent.com/29607818/69466186-2d720c00-0d38-11ea-8434-ba634858c3a1.png)

**Comment by Braiden-Psiuk** [comment]
Hi @jbadan, thanks for looking into this! Here's a demo for reference:
## Code
![code](https://user-images.githubusercontent.com/30049905/69551500-ce480d80-0f6a-11ea-898f-0991651a0ea1.png)
## Demo + Chrome Console
![demo](https://user-images.githubusercontent.com/30049905/69551839-6219d980-0f6b-11ea-9099-60ffa83f5287.png)
I understand that you cannot use the two properties together, but it seems that I can't use them at all. However, the _cols_ prop works. Did I maybe forget to import something?

**Comment by jbadan** [comment]
So with `no-gap`, please see the attached pr. There was a typo in the classname inside the component. 

`disableStyles` will only work if there is only one component on the page. All it is doing is preventing the injection of the style block into the head. Your `no-gap` example already injected it in to the head, so it's going to be available even if you add the `disableStyles` prop to any additional components.

This prop was mainly made for a use case where a consumer wants to be able to use the underlying logic/structure of the components with _no styles whatsoever_.

**Comment by Braiden-Psiuk** [comment]
Thank you very much for the clarification, makes sense now why it wasn't behaving the way I expected it to. I'll close this now.

**Comment by jbadan** [comment]
No problem! We should probably add some documentation clarifying this!
