### ISSUE TITLE
Ability to pass a default date to the DatePicker

### ISSUE THREAD

**Issue by SydneyMonis** [SAP/fundamental-react#822]
### Versions
**fundamental-react:** All
**fundamental-styles:** All

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by codefactor** [comment]
When will this get released?

We are considering using the DatePicker in SuccessFactors and the DatePicker obviously needs to have a value selected to begin with. It seems like a glaring issue.

**Comment by jbadan** [comment]
@codefactor There's a couple changes requested on the pull request, it will be merged as soon as it's approved.
