### ISSUE TITLE
DatePicker Popover should appear above the Input when there is not enough space

### ISSUE THREAD

**Issue by codefactor** [SAP/fundamental-react#828]
### Description

If you use a DatePicker near the bottom of the screen, even if there is not enough scroll area to see the popover it will always open below the input element. This is not the expected behavior, the Popup should appear above the input element in the case all of the following things are true:

1. there is not enough space within the scroll to show the popup below the input
2. there is more space above the input than below
3. there is enough space above the input to show the popup entirely

### Versions
**fundamental-react: all versions**
**fundamental-styles:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Fixed by rebuilding with Popover component in https://github.com/SAP/fundamental-react/pull/858
