### ISSUE TITLE
MultiInput always opens upwards and gets cut off at the top

### ISSUE THREAD

**Issue by codefactor** [SAP/fundamental-react#831]
### Description

I noticed this while using the following example page:
https://sap.github.io/fundamental-react/multiInput

Open the multi-input, for some reason it always opens above the input field. The selection list is cut off at the top so you cannot scroll through the list of items to see them all.

### Versions
**fundamental-react:**
**fundamental-styles:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
This is a 2 fold issue:

1. `.fd-popover__body--dropdown` needs some additional css - a max height and an overflow scroll.
1. We need to update react-popper once they finish migrating to popper v2 - https://github.com/popperjs/react-popper/pull/333
