### ISSUE TITLE
Calendar popup should close when date is selected

### ISSUE THREAD

**Issue by coding-my-passion** [SAP/fundamental-react#876]
### Description
 Currently user has to click outside in order to close calendar popup even after date from calendar is selected. Calendar popup should automatically close when date is selected.

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/858
