### ISSUE TITLE
FormTextarea: build out counter on component `fd-textarea-counter`

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental-react#880]
### Description
https://github.com/SAP/fundamental-styles/pull/419
https://fundamental-styles.netlify.com/components/form.html
![Screen Shot 2020-02-20 at 4 39 02 PM](https://user-images.githubusercontent.com/29607818/74993392-b106cc00-53ff-11ea-947e-5af01e71ecab.png)

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by smohtadi** [comment]
Hi @jbadan, I have some ideas about this, but would like to go by you first. I'm thinking about adding a prop to FormTextArea that represents the count limit. If set, display the counter. The text area would have an onchange event that updates the counter. So, it would be something like:
`<Textarea counter='150'><TextareaCounter>Characters left #count#</TextareaCounter></Textarea>`.
We then can either have function that looks for a keyword (e.g., #count#) and injects the value of the counter in that specific place, or just put it at the end of the string.
Let me know if I'm completely off or if this is more or less what you had in mind.

**Comment by jbadan** [comment]
@smohtadi That sounds like a great way to implement it. Make sure you follow the html from [fundamental-styles](https://fundamental-styles.netlify.com/components/form.html):
```
<textarea class="fd-textarea">Pellentesque metus lacus commodo eget justo ut rutrum varius nunc.</textarea>
<div class="fd-textarea-counter">150 characters left</div>
```

For the "characters left" string, we can default this to English for ease of use, but should add it via a `localizedText` prop like seen here in Counter: https://github.com/SAP/fundamental-react/blob/master/src/Counter/Counter.js#L36

Additionally, from the design spec: "The counter appears on all interaction states, except in Read-Only and Disabled state."

Thanks for contributing!
