### ISSUE TITLE
Calendar selected date, month, year style not updated on first click

### ISSUE THREAD

**Issue by prsdthkr** [SAP/fundamental-react#912]
### Description
When selecting a date from the calendar component, the selected style (blue with white text) is applied after a second click event on the page. On the first click the date gets a light grey background and stays that way until a second click happens anywhere on the page. This is true even when the calendar component is inside a popover. It is also true for month and year picker. Also, simulating a click using the browser console immediately applies the styles. 

**update:** seems to be due to keyboard focus. On selecting a date/month/year with mouse the focus is still on the selected item. The focus styles override the selected item styles. Using keyboard to navigate through the items revealed this.

Datepicker
![datepicker selected item](https://user-images.githubusercontent.com/43764832/75958344-de785e80-5e70-11ea-96b7-dfd67cdea3d0.gif)

Month picker
![month-picker](https://user-images.githubusercontent.com/43764832/75959417-11235680-5e73-11ea-8366-f77849953dd7.gif)

Year picker
![year-picker](https://user-images.githubusercontent.com/43764832/75959537-492a9980-5e73-11ea-8795-cc5453640d63.gif)

Working with console simulated click
![console-click](https://user-images.githubusercontent.com/43764832/75960163-6b70e700-5e74-11ea-9584-e270103ec039.gif)

### Versions
fundamental-react: v0.8.0
Chrome:  80.0.3987.132 (Official Build) (64-bit)
Firefox: 73.0.1 (64-bit)

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Do you think upgrading fundamental-styles to `0.8.0-rc.11` to include this pr will fix it? https://github.com/SAP/fundamental-styles/pull/506

**Comment by prsdthkr** [comment]
> Do you think upgrading fundamental-styles to `0.8.0-rc.11` to include this pr will fix it? [SAP/fundamental-styles#506](https://github.com/SAP/fundamental-styles/pull/506)

Yes

**Comment by prsdthkr** [comment]
Seems to be fixed as of `v0.11.0-rc.18`
