### ISSUE TITLE
Unable to set Initial time value for the Time Picker input.

### ISSUE THREAD

**Issue by athulvraj** [SAP/fundamental-react#915]
### Description
There is no provision to set an inital time value(default value) to the Time Picker Component.
According to the documentation, value prop can be used to set initial values but its not working. 

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by smohtadi** [comment]
Hi! I was planning on working on this issue but can't seem to replicate it. @athulvraj could you please let me know what input values do not work when passed to the value prop?

**Comment by jbadan** [comment]
fixed by https://github.com/SAP/fundamental-react/pull/917
