### ISSUE TITLE
@types/fundamental-react isn't compatible with fundamental-react 0.8.0

### ISSUE THREAD

**Issue by brainocean** [SAP/fundamental-react#916]
### Description
In npm.js, @types/fundamental-react's version is 0.8.0, but after I download it via npm install, it still has component types which are removed from fundamental-react 0.8.0, for example Alert, ListGroup etc.

### Versions
**fundamental-react:** 
0.8.0

---

![2020-03-06_17-55-47](https://user-images.githubusercontent.com/1978334/76072994-e1d82b00-5fd3-11ea-80f4-6f9a51c062f8.png)

**Comment by jbadan** [comment]
Hi @brainocean - the core maintainers of this library do not maintain @types/fundamental-react
