### ISSUE TITLE
DatePicker - When using the Range filter, there must be a way to clear the range

### ISSUE THREAD

**Issue by coding-my-passion** [SAP/fundamental-react#928]
### Description
There can be a button called 'Clear' in the popup Calendar.

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Does that match the fiori3 spec? If it is, this is a change that would need to occur in fundamental-styles first.

**Comment by coding-my-passion** [comment]
Hi @jbadan I checked fiori 3 spec for date-picker https://experience.sap.com/fiori-design-web/date-picker/. It seems like above feature request does not match fiori 3 spec. So closing the issue. Thanks!
