### ISSUE TITLE
How to capture "onchange" event from FormSelect component

### ISSUE THREAD

**Issue by superwangnan** [SAP/fundamental-react#929]
Hi team,
I use the ui5 fundamental react to create a very simple UI and add FormSelect in it. I added the event listener on 'onchange' event. but it has never been trigger. Any idea about that?
I use this code to generate formselect:
``` javascript
  function genSelectItems(items, itemId, refO) {
    const listItems = items.map((item) =>
      <option key={item} value={item}>{item}</option>
    );
    return <FormSelect id={itemId} ref={refO}>{listItems}</FormSelect>
  };
```
I added the FormSelect in page
``` javascript
    <FormItem>
                      <FormLabel htmlFor="input-2" required> 健康状态 </FormLabel>
                      {genSelectItems(status, "input-2", inputStatus)}
                    </FormItem>
```
I defined event handler
```javascript
  const handleInputStatus = useCallback( event => {
    console.log(sick)
    // setSick(
    //   sick => {
    //     if (inputStatus.current.value ===  "健康")
    //       return {display: "none"};
    //     else 
    //       return {display: "block"}
    //   }
    // );

  },[setSick]);
```
bind the event
```javascript
  useEffect(() => {
    console.log(inputStatus.current)
    inputStatus.current.addEventListener('onclick',handleInputStatus);
    return () => {
      inputStatus.current.removeEventListener('onchange',handleInputStatus);
    }
  }, [handleInputStatus])
```
I select the different value in select control, but the handler doesn't fired. 

BTW: any suggestion for debug the react code? I am really new on it.

Thanks so much.

**Comment by skvale** [comment]
The `FormSelect` is a wrapper around the HTML `<select>` component.

`<select>` has an `onSelect` prop, so you could listen to the change via

```js
<FormSelect onSelect={e => { console.log('you selected', e.target.value) }} />
```

**Comment by jbadan** [comment]
Closing this issue for @skvale's solution. @superwangnan feel free to reopen if you don't feel that answers your question.
