### ISSUE TITLE
Datepicker - Trigger the onBlur event when the Datepicker closes

### ISSUE THREAD

**Issue by coding-my-passion** [SAP/fundamental-react#930]
### Description
Currently, for a normal datepicker, when we click on a date, it closes but onBlur isn't triggered till we click somewhere else on the page.

A similar thing happens on the Range based Datepicker.

### Versions
**fundamental-react:**0.8.1

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
@coding-my-passion Can you finish filling out the template with what version of fundamental-react you're using? Thanks!

**Comment by bcullman** [comment]
i would think that onblur should fire once you leave the input field focus, not when the calendar closes.

**Comment by coding-my-passion** [comment]
@jbadan Earlier I created issue #876 to close date-picker when date from calendar is selected. Later we closed issue #876 and it was linked with issue #858 
But with latest version of fundamental-react - 0.8.1, I noticed that issue #876 is not resolved. 
Any idea?
Thanks!

**Comment by jbadan** [comment]
Hi @coding-my-passion - can you elaborate? It looks like #876 is resolved when I try on the docs site. I think I'm missing something. 
![2020-03-26 07 10 53](https://user-images.githubusercontent.com/29607818/77656471-2a2e9d00-6f31-11ea-8b45-6733891767a9.gif)

**Comment by coding-my-passion** [comment]
Hey @jbadan my fault, sorry for that. I checked in wrong version of fundamental-react.

For this feature request, if I trigger the onBlur event whenever the datepicker closes then onBlur props will be executed twice. First when datepicker closes and second when we click somewhere else on the page.

Can we add new prop something like `onDatePickerClose` to fix this issue.

Can you please suggest which is a better option?
Thanks!

**Comment by jbadan** [comment]
@jacobdevera did https://github.com/SAP/fundamental-react/pull/936 fix this issue with `onBlur`?

**Comment by jacobdevera** [comment]
@jbadan No, it fixed a separate issue where `onBlur` would fire when clicking anywhere outside. 

I think I agree with @bcullman that `onBlur` should only fire when leaving the input field to avoid having it fire twice. A separate `onDatePickerClose` callback seems fair.

**Comment by coding-my-passion** [comment]
Thank you @jacobdevera @jbadan @bcullman for your help. I have created PR  https://github.com/SAP/fundamental-react/pull/939. Please review.
