### ISSUE TITLE
Search Input getting error in the console ,not recognize the `addonBefore &  x-out-ofboundaries

### ISSUE THREAD

**Issue by benoron** [SAP/fundamental-react#931]
### Description

**1. when opening the search popover** 
1540 Warning: React does not recognize the `addonBefore` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `addonbefore` instead. If you accidentally passed it from a parent component, remove it from the DOM element....
<img width="884" alt="Screen Shot 2020-03-25 at 7 36 47" src="https://user-images.githubusercontent.com/2092131/77505295-6e576a00-6e6b-11ea-808a-a6cb1a8e4de3.png">

**2. when scrolling out of the screen with an open popover.**
Warning: Received `true` for a non-boolean attribute `x-out-of-boundaries`.
If you want to write it to the DOM, pass a string instead: x-out-of-boundaries="true" or x-out-of-boundaries={value.toString()}...
<img width="923" alt="image001" src="https://user-images.githubusercontent.com/2092131/77505288-6bf51000-6e6b-11ea-842f-7067b4425766.png">
 
Thanks 
Ben Oron 
Front End Developer, 
SAP Fieldglass,

### Versions
**fundamental-react:**
0.8
---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by smohtadi** [comment]
Hi @jbadan, can I work on this?

**Comment by jbadan** [comment]
@smohtadi go for it!
