### ISSUE TITLE
search input not closed after select item 

### ISSUE THREAD

**Issue by BenOron** [SAP/fundamental-react#938]
### Description

search input not closed after select item 
### Versions
**fundamental-react:**
0.8
---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by benoron** [comment]
Hi @jbadan, can I work on this?
need some help with pull req flow.
