### ISSUE TITLE
On the TimePicker component, whenever focus is lost from the field, the field gets cleared

### ISSUE THREAD

**Issue by coding-my-passion** [SAP/fundamental-react#965]
### Description
On the TimePicker component, if there is a default time or when we set a time, if we click elsewhere such that focus is lost from the field, the field gets cleared.

### Versions
**fundamental-react:**v0.8.1

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by skvale** [comment]
![lost-value](https://user-images.githubusercontent.com/5314713/79225994-3f596600-7e23-11ea-87ad-da8db3eb686f.gif)
