### ISSUE TITLE
ListItem "selected" prop not working

### ISSUE THREAD

**Issue by markoromandic** [SAP/fundamental-react#970]
### Description
ListItem prop "selected" is not working. Due to that ListItem cannot be Controlled component. I connected state(boolean value) to the "selected" prop, but when I update the state, the styling is not changed. Styling is only changed if you click on the component.

### Versions
**fundamental-react:**
v0.8.1

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by prsdthkr** [comment]
Should be fixed in [0.13.0-rc.0](https://github.com/SAP/fundamental-react/commit/4b32a667d6428730ef5ae3a510099128e0c46056)
