### ISSUE TITLE
DatePicker: Unknown event handler property `onDatePickerClose`

### ISSUE THREAD

**Issue by rkl1994** [SAP/fundamental-react#974]
### Description
While using component DatePicker, there will be an error message in the console said 'Unknown event handler property `onDatePickerClose`' no matter in my application or in the storybook website.
https://deploy-preview939---fundamental-react.netlify.app/datepicker
<img width="450" alt="Screen Shot 2020-04-24 at 4 26 04 PM" src="https://user-images.githubusercontent.com/5527455/80191488-5af51580-8648-11ea-9784-ae74c90b8b9d.png">

I'd like to know how to fix it. Thanks.

### Versions
**fundamental-react:*0.9.0*

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by DusanSacha** [comment]
I analyzed the warning and I think the event handler 'onDatePickerClose' must be explicitly defined as a variable in [the render function of DatePicker Component](https://github.com/SAP/fundamental-react/blob/9708222c81f8f69414955b1437fc1079c8f2a554/src/DatePicker/DatePicker.js#L301)

The reason why this warning appears is described here: 
https://reactjs.org/warnings/unknown-prop.html

I can create a pull request with a fix for this issue.
