### ISSUE TITLE
unique "key" prop is missing in menu item

### ISSUE THREAD

**Issue by BenOron** [SAP/fundamental-react#999]
### Description
When using the  Menu  from 'fundamental-react/Menu';
Receive error in the console.

`react_devtools_backend.js:6 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Menu.Item`. See https://fb.me/react-warning-keys for more information.
    in span (created by Menu.Item)
    in Menu.Item
    in ul (created by Menu.List)
    in Menu.List
    in nav (created by Menu)
    in Menu`

![Screen Shot 2020-05-05 at 15 13 48](https://user-images.githubusercontent.com/2092131/81064848-163c6a80-8ee3-11ea-86ab-9a1ce9840b1d.png)

### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Hi Ben! Can you provide a code sample too? Thank you

**Comment by BenOron** [comment]
Hi Jenna,
You can see it reproduced here: 
 https://sap.github.io/fundamental-react/menu

**Comment by jbadan** [comment]
Oh ok thank you! That should just be a documentation site error, we've rebuilt the docs recently (yesterday! 😆 ) so that is resolved by https://github.com/SAP/fundamental-react/pull/978 and will be populated to sap.github.io/fundamental-react on the 0.10.0 release 

Feel free to reopen if you don't agree!

**Comment by pavelkornev** [comment]
Using fundamental-react v0.12, experiencing the same issue...

**Comment by jbadan** [comment]
@pavelkornev This issue was related to a documentation example. If you're mapping through Menu.Items to render them, you're going to need to provide your own keys. Are you seeing this error in one of our examples? Or could you provide a code sample where you're seeing this?

**Comment by jbadan** [comment]
Oh ok, I see. It's coming from https://github.com/SAP/fundamental-react/blob/master/src/Menu/_MenuItem.js#L80, do you mind opening a new issue about this? Thanks!
